access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
sudo: required
language: generic

services:
   - docker

before_install:
   - docker build -t beasantillana/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true beasantillana/docker-react npm run test

   
deploy:
   provider: elasticbeanstalk
   region: 'us-east-1'
   app: 'docker'
   env: 'docker-env'
   bucket_name: 'elasticbeanstalk-us-east-1-429625873162'
   bucket_path: 'docker"
   on:
      branch: main
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY 
