sudo: required
 language: generic

 services:
   - docker

 before_install:
   - docker build -t beasantillana/docker-react -f Dockerfile.dev .

 script:
   - docker run -e CI=true beasantillana/docker-react npm run test